/**
 * WFS Transaction (WFS-T) Routes
 * Provides transactional WFS support for editing features
 */

const { requireRole } = require('../middleware/jwtAuth')
const { publicLayerTables } = require('../utils/publicLayers')

const KEY_COLUMNS = ['id', 'fid', 'gid']
const INTEGER_TYPES = new Set(['int2', 'int4', 'int8'])

function sanitizeIdentifier(name) {
  const s = String(name || '')
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 48)
  return s && /^[a-z_]/.test(s) ? s : null
}

function isPrivateTable(tableName) {
  const privatePrefixes = ['users', 'audit', 'sessions', 'password', 'mfa', 'auth', 'api_keys']
  const lower = tableName.toLowerCase()
  return privatePrefixes.some(p => lower.startsWith(p)) || lower.includes('token') || lower.includes('secret')
}

const quoteIdent = (name) => `"${String(name).replace(/"/g, '""')}"`

const badRequest = (message) => Object.assign(new Error(message), { statusCode: 400 })

// Column names are never taken from the request: property keys are matched
// against the table's real columns, and anything else is ignored. The key
// column (used by update/delete) is the first of id/fid/gid the table has.
async function describeTable(pg, table) {
  const { rows } = await pg.query(
    `SELECT column_name, udt_name, is_nullable, column_default FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = $1`,
    [table]
  )
  const geomColumn = rows.find((r) => r.udt_name === 'geometry')?.column_name || null
  const attributes = new Map(
    rows
      .filter((r) => r.udt_name !== 'geometry' && r.udt_name !== 'geography')
      .map((r) => [r.column_name, r.udt_name])
  )
  const keyColumn = KEY_COLUMNS.find((k) => attributes.has(k)) || null
  const keyRow = rows.find((r) => r.column_name === keyColumn)
  // A NOT NULL key with no default cannot be generated by the database, and
  // this endpoint never accepts a client-chosen key.
  const keyNeedsValue = !!keyRow && keyRow.is_nullable === 'NO' && !keyRow.column_default

  let geomType = null
  let geomSrid = 4326
  if (geomColumn) {
    const { rows: g } = await pg.query(
      `SELECT type, srid FROM geometry_columns
       WHERE f_table_schema = 'public' AND f_table_name = $1 AND f_geometry_column = $2`,
      [table, geomColumn]
    )
    if (g.length) {
      geomType = String(g[0].type || '').toUpperCase()
      if (g[0].srid > 0) geomSrid = g[0].srid
    }
  }
  return { geomColumn, attributes, keyColumn, keyNeedsValue, geomType, geomSrid }
}

// The incoming GeoJSON is WGS 84. Convert to the column's SRID, and promote a
// single geometry to a Multi* one when the column holds multi-geometries (the
// editor draws single polygons/lines/points).
function geometrySql(schema, placeholder) {
  let expr = `ST_SetSRID(ST_GeomFromGeoJSON(${placeholder}), 4326)`
  if (schema.geomSrid !== 4326) expr = `ST_Transform(${expr}, ${Number(schema.geomSrid)})`
  if (schema.geomType && schema.geomType.startsWith('MULTI')) expr = `ST_Multi(${expr})`
  return expr
}

function editableProperties(props, attributes) {
  return Object.keys(props || {}).filter(
    (k) => attributes.has(k) && !KEY_COLUMNS.includes(k.toLowerCase())
  )
}

function keyValue(schema, id) {
  const type = schema.attributes.get(schema.keyColumn)
  if (INTEGER_TYPES.has(type) && !/^-?\d+$/.test(String(id))) {
    throw badRequest(`Invalid ${schema.keyColumn} value: ${id}`)
  }
  return id
}

function requireKeyColumn(schema) {
  if (!schema.keyColumn) {
    throw badRequest('This layer has no id, fid or gid column; it cannot be updated or deleted')
  }
}

function asArray(value, name) {
  if (value === undefined || value === null) return []
  if (!Array.isArray(value)) throw badRequest(`${name} must be an array`)
  return value
}

async function createWFSTransactionRoutes(server) {
  // POST /api/ogc/wfs/transaction
  server.post('/api/ogc/wfs/transaction', {
    preHandler: requireRole(server, ['planner', 'gis_officer', 'admin']),
  }, async (request, reply) => {
    const { typeName, features, insert, update, delete: deleteFeatures } = request.body || {}

    if (!typeName) {
      return reply.status(400).send({
        success: false,
        error: 'typeName is required',
      })
    }

    const base = sanitizeIdentifier(typeName)
    if (!base) {
      return reply.status(400).send({
        success: false,
        error: 'Invalid typeName',
      })
    }

    try {
      // Resolve table name
      let { rows: tables } = await server.pg.query(
        `SELECT table_name FROM information_schema.tables
         WHERE table_schema = 'public' AND table_name = ANY($1)
         ORDER BY (table_name = $2) DESC LIMIT 1`,
        [[base, `qgis_${base}`], base]
      )

      if (!tables.length) {
        return reply.status(404).send({
          success: false,
          error: 'Layer not found',
        })
      }

      const table = tables[0].table_name

      // Check permissions - only allow editing of qgis_* staging tables or authorized spatial layers
      const allowed = table.startsWith('qgis_') || (await publicLayerTables(server.pg)).includes(table)
      if (!allowed || isPrivateTable(table)) {
        return reply.status(403).send({
          success: false,
          error: 'Not authorized to edit this layer',
        })
      }

      // (checked against the table schema below, before any write)
      const inserts = insert ? asArray(insert, 'insert') : asArray(features, 'features').filter((f) => !f.id)
      const updates = update ? asArray(update, 'update') : asArray(features, 'features').filter((f) => f.id)
      const deletes = asArray(deleteFeatures, 'delete')

      const schema = await describeTable(server.pg, table)
      if (!schema.geomColumn) {
        return reply.status(400).send({ success: false, error: 'Layer has no geometry column' })
      }
      if (inserts.some((f) => f.geometry) && schema.keyNeedsValue) {
        return reply.status(400).send({
          success: false,
          error: `New features cannot be added to this layer: its ${schema.keyColumn} column has no default value`,
        })
      }
      const geom = quoteIdent(schema.geomColumn)
      const tbl = quoteIdent(table)

      const client = await server.pg.connect()
      let inserted = 0, updated = 0, deleted = 0

      try {
        await client.query('BEGIN')

        // Handle INSERT operations
        for (const feature of inserts) {
          if (!feature.geometry) continue

          const colNames = editableProperties(feature.properties, schema.attributes)
          const cols = [...colNames.map(quoteIdent), geom]
          const placeholders = colNames
            .map((_, i) => `$${i + 1}`)
            .concat([geometrySql(schema, `$${colNames.length + 1}`)])
          const values = [...colNames.map((c) => feature.properties[c]), JSON.stringify(feature.geometry)]

          await client.query(
            `INSERT INTO ${tbl} (${cols.join(', ')}) VALUES (${placeholders.join(', ')})`,
            values
          )
          inserted++
        }

        // Handle UPDATE operations
        for (const feature of updates) {
          if (!feature.id || !feature.geometry) continue
          requireKeyColumn(schema)

          const setClauses = []
          const values = []
          let idx = 1

          for (const k of editableProperties(feature.properties, schema.attributes)) {
            setClauses.push(`${quoteIdent(k)} = $${idx++}`)
            values.push(feature.properties[k])
          }
          setClauses.push(`${geom} = ${geometrySql(schema, `$${idx++}`)}`)
          values.push(JSON.stringify(feature.geometry))
          values.push(keyValue(schema, feature.id))

          const result = await client.query(
            `UPDATE ${tbl} SET ${setClauses.join(', ')} WHERE ${quoteIdent(schema.keyColumn)} = $${idx}`,
            values
          )
          updated += result.rowCount || 0
        }

        // Handle DELETE operations
        for (const del of deletes) {
          if (!del.id) continue
          requireKeyColumn(schema)
          const result = await client.query(
            `DELETE FROM ${tbl} WHERE ${quoteIdent(schema.keyColumn)} = $1`,
            [keyValue(schema, del.id)]
          )
          deleted += result.rowCount || 0
        }

        await client.query('COMMIT')

        return reply.send({
          success: true,
          data: {
            inserted,
            updated,
            deleted,
            total: inserted + updated + deleted,
          },
        })
      } catch (error) {
        await client.query('ROLLBACK')
        throw error
      } finally {
        client.release()
      }
    } catch (error) {
      if (error.statusCode === 400) {
        return reply.status(400).send({ success: false, error: error.message })
      }
      request.log.error({ err: error }, '[WFS-T] Transaction failed')
      return reply.status(500).send({
        success: false,
        error: 'Transaction failed',
        details: error.message,
      })
    }
  })
}

module.exports = { createWFSTransactionRoutes }
