-- Migration 136: give proposed_peri_urban_zones.id a value source
--
-- `id` is `integer NOT NULL` with no DEFAULT and no sequence. Nothing supplies
-- it, so any INSERT that does not pass an explicit id fails:
--
--   null value in column "id" of relation "proposed_peri_urban_zones"
--   violates not-null constraint
--
-- Two callers hit this, and the second is the one that matters:
--
--   1. POST /api/zones (src/routes/zones.js). Dead since migration 113
--      repointed it at the canonical table. Zone creation through the API has
--      never worked since.
--
--   2. **Drawing a new zone in QGIS Desktop.** qgis-projects/vungu-project.qgs
--      binds the zones layer to `zones_master` with key='id', and zones_master
--      selects that column straight through. QGIS does not invent values for an
--      integer primary key on a PostGIS layer, so adding a feature fails on the
--      NOT NULL constraint. Editing existing zones is unaffected, which is why
--      this went unnoticed -- the live-sync tests only ever edit.
--
--      This is the authoring route the whole pipeline is built around: a planner
--      draws a zone in QGIS, the web map updates. That path was broken at the
--      first step.
--
-- A plain sequence + DEFAULT rather than GENERATED BY DEFAULT AS IDENTITY:
-- ADD IDENTITY rewrites the table, and there is no reason to rewrite 36 rows
-- with geometries to obtain something a sequence already gives. The sequence is
-- OWNED BY the column so a future DROP of the table takes it with it.
--
-- Existing ids are not touched. setval starts the sequence one past the current
-- maximum, so the next insert is 37 rather than colliding with an existing row.
--
-- Idempotent: safe to re-run.
-- Apply locally with: node scripts/apply-local-migration.js 136_zones_id_sequence.sql

BEGIN;

CREATE SEQUENCE IF NOT EXISTS public.proposed_peri_urban_zones_id_seq;

-- setval before SET DEFAULT so a re-run cannot walk the sequence backwards:
-- GREATEST(..., 1) means an empty table starts at 1, and never below the
-- current max even if this runs twice.
SELECT setval(
  'public.proposed_peri_urban_zones_id_seq',
  GREATEST(COALESCE((SELECT MAX(id) FROM public.proposed_peri_urban_zones), 0), 1),
  true
);

ALTER TABLE public.proposed_peri_urban_zones
  ALTER COLUMN id SET DEFAULT nextval('public.proposed_peri_urban_zones_id_seq'::regclass);

ALTER SEQUENCE public.proposed_peri_urban_zones_id_seq
  OWNED BY public.proposed_peri_urban_zones.id;

COMMENT ON COLUMN public.proposed_peri_urban_zones.id IS
  'Zones PK. Value supplied by proposed_peri_urban_zones_id_seq; QGIS Desktop cannot invent one when a planner draws a new zone.';

COMMIT;
